import torch

from flash_attn import *

local_flash_attn_qkvpacked_func = flash_attn_qkvpacked_func
local_flash_attn_kvpacked_func = flash_attn_kvpacked_func
local_flash_attn_func = flash_attn_func
local_flash_attn_varlen_qkvpacked_func = flash_attn_varlen_qkvpacked_func
local_flash_attn_varlen_kvpacked_func = flash_attn_varlen_kvpacked_func
local_flash_attn_varlen_func = flash_attn_varlen_func
local_flash_attn_with_kvcache = flash_attn_with_kvcache
